Login/Controllers/MasterDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Login.Data;
using Login.Models;

namespace Login.Controllers
{
    public class MasterDataController : Controller
    {
        private readonly DataContext _context;

        public MasterDataController(DataContext context)
        {
            _context = context;
        }

        // GET: MasterData
        public async Task<IActionResult> Index()
        {
              return View(await _context.Master_Data.ToListAsync());
        }

        // GET: MasterData/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Master_Data == null)
            {
                return NotFound();
            }

            var master_Data = await _context.Master_Data
                .FirstOrDefaultAsync(m => m.PERSONID == id);
            if (master_Data == null)
            {
                return NotFound();
            }

            return View(master_Data);
        }

        // GET: MasterData/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MasterData/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PERSONID,POPULATIONREGISTERNO,TAXREGISTERNO,PASSPORTNO,KITAS,FULL_NAME,PHONE,GENDER,EMAIL,BIRTHDATE,HIGHSCHOOL,UNIVERSITY,UNIVERSITYMAJOR,MSSCHOOL,MSMAJOR,PHDSCHOOL,PHDMAJOR,POSITION,COUNTRYCODE,PROVINCECODE,ADDRESS,CITY,POSTALCODE,BUSINESS_REG_NO,OCCUPATION,LOC_ASING,NASIONALITY,DateCreated")] Master_Data master_Data)
        {
            if (ModelState.IsValid)
            {
                _context.Add(master_Data);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(master_Data);
        }

        // GET: MasterData/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Master_Data == null)
            {
                return NotFound();
            }

            var master_Data = await _context.Master_Data.FindAsync(id);
            if (master_Data == null)
            {
                return NotFound();
            }
            return View(master_Data);
        }

        // POST: MasterData/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PERSONID,POPULATIONREGISTERNO,TAXREGISTERNO,PASSPORTNO,KITAS,FULL_NAME,PHONE,GENDER,EMAIL,BIRTHDATE,HIGHSCHOOL,UNIVERSITY,UNIVERSITYMAJOR,MSSCHOOL,MSMAJOR,PHDSCHOOL,PHDMAJOR,POSITION,COUNTRYCODE,PROVINCECODE,ADDRESS,CITY,POSTALCODE,BUSINESS_REG_NO,OCCUPATION,LOC_ASING,NASIONALITY,DateCreated")] Master_Data master_Data)
        {
            if (id != master_Data.PERSONID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(master_Data);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Master_DataExists(master_Data.PERSONID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(master_Data);
        }

        // GET: MasterData/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Master_Data == null)
            {
                return NotFound();
            }

            var master_Data = await _context.Master_Data
                .FirstOrDefaultAsync(m => m.PERSONID == id);
            if (master_Data == null)
            {
                return NotFound();
            }

            return View(master_Data);
        }

        // POST: MasterData/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Master_Data == null)
            {
                return Problem("Entity set 'DataContext.Master_Data'  is null.");
            }
            var master_Data = await _context.Master_Data.FindAsync(id);
            if (master_Data != null)
            {
                _context.Master_Data.Remove(master_Data);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Master_DataExists(int id)
        {
          return _context.Master_Data.Any(e => e.PERSONID == id);
        }

    }
}

Login/Controllers/SendController.cs
using Microsoft.AspNetCore.Mvc;

namespace Login.Controllers
{
    public class SendController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Login/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Data SID SIPETRO OJK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<style>
    .left {
        position: relative;
        margin-left: 87%;
    }

    .dropdown-menu {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
        top: 45px;
    }

    .dropdown-menu li {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        cursor: pointer;
    }

    .dropdown-menu li:hover {
        background-color: #ddd;
    }

    /* Show the dropdown menu on hover */
    .dropdown:hover .dropdown-menu {
        display: block;
    }
</style>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="dropdown">
                <button class="btn dropdown-toggle text-light fw-bold dropbtn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Data SID SIPETRO OJK
                </button>
                <ul class="dropdown-menu mx-3">
                    <li>@Html.ActionLink("Transfer Data", "Index", "Transfer", new{}, new{@class="dropdown-item"})</li>
                    <li>@Html.ActionLink("Generate Data", "Index", "Generate", new{}, new{@class="dropdown-item"})</li>
                    <li>@Html.ActionLink("Send Data", "Index", "Send", new{}, new{@class="dropdown-item"})</li>
                    <li>@Html.ActionLink("Master Data", "Index", "MasterData", new{}, new{@class="dropdown-item"})</li>
                </ul>
                </div>
                <div class="navbar-collapse collapse d-flex justify-content-end">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-light fw-bold me-3" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <button class="btn dropdown-toggle text-light" type="button" data-bs-toggle="dropdown">
                                Hello, Admin <i class="fa-regular fa-circle-user"></i>
                            </button>
                            <div class="dropdown-menu left">
                                @Html.ActionLink("Logout", "Login", "Login", new{}, new{@class="dropdown-item"})
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Login/Views/Shared/_LayoutFullPage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Data SID SIPETRO OJK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<div class="">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
</html>